### ISSUE TITLE
add link to download reliability data

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#26]
metadata that Chris requested and file locations are here: https://docs.google.com/spreadsheets/d/1cn3EZxMqeQAbt0eRMhi3QJX5MPoRs7DMLkfiWfj1k0E/edit?usp=sharing

**Comment by mmolta** [comment]
Add section below 'Outputs' in the about section that is titled 'Sources' and just has a link that says 'view and download reliability data' and links to the Open Data portal with the above data uploaded to it. @todo talk to GIS about updating Open Data

**Comment by mmolta** [comment]
@crvanpollard @seandoesgis is there a link on open data for this?

**Comment by crvanpollard** [comment]
@smoran3 @mmolta These dataset will not be published to DVRPC's Open Data so someone needs to place these zipped datasets into a Google Drive location and enable sharing and provide that sharable link

U:\FY2018\Transportation\TransitBikePed\TransitPrioritySetting\geojson.zip

U:\FY2018\Transportation\TransitBikePed\TransitPrioritySetting\shapefiles.zip

**Comment by crvanpollard** [comment]
DVRPC_RTSP_shapefile.zip file stored in C.Pollard's google drive "GIS Data Sharing/FY2091/RTSP"

https://drive.google.com/drive/folders/1aXwLVweE9xqqZgYIgT6ZC3XREJRwgfHB?usp=sharing

**Comment by crvanpollard** [comment]
Here is the link for the actual zipfile
https://drive.google.com/file/d/1att6x8W4Zea_gHKsoFjlL_AHBTwi0FXc/view?usp=sharing
