### ISSUE TITLE
Copy reliability regional layers to route detail tab

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#29]
so they can also be filtered. Let's see if there is a way to differentiate them a little bit. Or should there be the same filter, maybe lower and less prominent, on the regional layers tab? I'm open to ideas here.

**Comment by mmolta** [comment]
note that we will revisit this after web products review if necessary

**Comment by smoran3** [comment]
we got feedback on this during the review process, so we can revisit it now. just copy the regional layers to the bottom of the route detail layer list. Add text at end of regional layers intro paragraph: "These layers can also be filtered by route on the Route Detail tab."
