### ISSUE TITLE
Update Gap results in droplet

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#31]
(I will provide this and update you when it's ready)
will include:
- changes to scoring of transfers
- changes to window of average transfer wait time calculation
- potentially peak and daily average option?

**Comment by smoran3** [comment]
also update documentation pdf

**Comment by smoran3** [comment]
I sent these updated tables to Mike this morning after he sent me the schema so I could copy it. He said he would pop them in this afternoon. The table called `odgaps_ts_s_trim` has an additional column called "DailyVols" that can be used for that demand sentence we talked about.

**Comment by smoran3** [comment]
The updated documentation PDF to go along with this fix is attached
[TransitNetworkGapAnalyzer.pdf](https://github.com/dvrpc/RTPS/files/3173967/TransitNetworkGapAnalyzer.pdf)

**Comment by mmolta** [comment]
PDF updated

**Comment by mmolta** [comment]
With the PDF and droplet updated, I'm going to close this because #33 handles the demand sentence from "DailyVols"
