### ISSUE TITLE
holes in Reliability layer in Trenton

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#43]
This is also an issue in the shapefile I have. I'm tracing my steps to see where this fell out, but it will likely lead to a vector tile update once I figure it out.

**Comment by smoran3** [comment]
the updated db table that needs to dropped in is located here: \\DAISY\BikePedTransit\RTPS\DB_backup\reliability_update_060619.backup

the shapefile with only geometries and 'gid' to join this table to is here: U:/FY2018/Transportation/TransitBikePed/TransitPrioritySetting/shapefiles/Reliability/Webmap/geom_tojoin/rel_ndlinks_score_t2.shp

This also impacts the shapefiles I gathered to post for public download, so I'll include that update in my response to Chris.

**Comment by mmolta** [comment]
@seandoesgis  @crvanpollard can you guys help with this one?

**Comment by crvanpollard** [comment]
@smoran3 can you please double check the location where you were having gap issues. The latest Vector Tile push should have filled these holes

**Comment by smoran3** [comment]
Have all the zoom levels (of whatever the proper name for them is) been generated for the new vector tiles? I still see holes in Trenton, but when I zoom in farther, they get filled in.
Holes:
![image](https://user-images.githubusercontent.com/22378781/60286307-7b93f800-98dd-11e9-8af4-e8eaddddd545.png)
No holes:
![image](https://user-images.githubusercontent.com/22378781/60286474-9fefd480-98dd-11e9-9bf9-ccdf6a2ecb92.png)

**Comment by mmolta** [comment]
issue is resolved, vt cache will persist for a little bit
