### ISSUE TITLE
Add layer description on regional layers tab (reliability)

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#55]
Show under the legend (maybe within the legend box if possible).
**Reliability Score:** A composite measure of TTI, OTP, and scheduled speed. High reliability score identifies segments that may benefit from targeted improvements to transit operations.
**Reliability Score Weighted by Ridership:** Results weighted by ridership to highlight unreliable segments that impact the most passengers.
**Travel Time Index:** TTI is the ratio of peak hour travel time to free flow travel time.

**Comment by mmolta** [comment]
closed w/merge
