### ISSUE TITLE
Update vector tiles

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#56]
Need to add new/cleaned up version of Average Scheduled Speed. I will let you know where this is when it's ready.

**Comment by smoran3** [comment]
These two shapefiles have been edited and are ready to be included in the vector tile update (and in the downloadable shapefiles on the gis portal). I just deleted features that didn't need to be there, so fields should all be the same:
U:\FY2018\Transportation\TransitBikePed\TransitPrioritySetting\shapefiles\ForPublicDownload\ReliabilityScore.shp
U:\FY2018\Transportation\TransitBikePed\TransitPrioritySetting\shapefiles\ForPublicDownload\SurfaceTransitScheduledSpeed.shp

**Comment by seandoesgis** [comment]
Updated
