### ISSUE TITLE
Update documentation PDFs

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#58]
[HigherFrequencyScenario.pdf](https://github.com/dvrpc/RTPS/files/3407053/HigherFrequencyScenario.pdf)
[SurfaceTransitReliability.pdf](https://github.com/dvrpc/RTPS/files/3407054/SurfaceTransitReliability.pdf)
[TransitNetworkGapAnalyzer.pdf](https://github.com/dvrpc/RTPS/files/3407055/TransitNetworkGapAnalyzer.pdf)
[WheelchairAcessibility.pdf](https://github.com/dvrpc/RTPS/files/3407056/WheelchairAcessibility.pdf)

**Comment by mmolta** [comment]
pdf's updated
