### ISSUE TITLE
update tab title and other branding

### ISSUE THREAD

**Issue by smoran3** [dvrpc/RTPS#59]
when website is open, the tab is still called Regional Transit _Priority_ Platform, instead of _Screening_.

Also - the link is still /rtps. Is there a way to make that redirect to an /rtsp so we don't have to share a new link, or is that not worth it?

Also - Addison found that at the bottom of the maps, it says Regional Transit Priority setting (see attached screenshot)
![rtsp](https://user-images.githubusercontent.com/22378781/61733691-54024500-ad4e-11e9-9319-2de5701a095c.png)

**Comment by mmolta** [comment]
closed w/merge now that VT update changed map overlay
